name: Front CI
on:
  push:
    paths: [ 'front/**' ]
  pull_request:
    paths: [ 'front/**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          sparse-checkout: |
            front
      - name: Install pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          package_json_file: front/package.json
      - name: "Set up Node.js"
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          cache: 'pnpm'
          node-version-file: front/.node-version
          cache-dependency-path: front/pnpm-lock.yaml
      - name: "Install dependencies"
        run: pnpm install
      - name: "Run check"
        run: pnpm check
      - name: "Build"
        run: pnpm build
