name: Front CI
on:
  push:
    paths: [ 'front/**' ]
  pull_request:
    paths: [ 'front/**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          sparse-checkout: |
            front
      - name: Install pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          package_json_file: front/package.json
      - name: "Set up Node.js"
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          cache: 'pnpm'
          node-version-file: front/.node-version
          cache-dependency-path: front/pnpm-lock.yaml
      - name: "Install dependencies"
        run: pnpm install
      - name: "Run check"
        run: pnpm check
      - name: "Build"
        run: pnpm build
